name: yesod-routes-metrics
version: '0.2.0.0'
synopsis: Parser Yesod routes file and compute route access metrics for Yesod
description: README.md
category: Web
author: James M.C. Haver II
maintainer: mchaver@gmail.com
copyright: 2017 Plow Technologies
license: BSD3
github: plow-technologies/yesod-routes-metrics

library:
  source-dirs: src
  exposed-modules: 
  - Yesod.Routes.Metrics
  - Yesod.Routes.Convert
  - Yesod.Routes.Convert.Internal  
  - Yesod.Routes.Parser.Internal
  - Yesod.Routes.Util  
  dependencies:
  - base >= 4.7 && < 5
  - bytestring  
  - containers
  - ekg-core
  - http-types
  - text
  - time
  - yesod-core
  - wai
  ghc-options:
  - -Wall
  - -Werror

tests:
  yesod-routes-metrics-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - base >= 4.7 && < 5
    - containers
    - ekg-core
    - hspec
    - http-types
    - network
    - vault
    - yesod-core
    - yesod-routes-metrics
    - wai
    